# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  # random utilities
  - name: utils
    before: |
      sudp apt-get install tree
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
  - name: update-utils
    before: |
      sudo apt update &&
      sudo apt upgrade -y 
  - name: Install Amplify CLI
    before: |
      npm add --save-dev @aws-amplify/backend@latest @aws-amplify/backend-cli@latest typescript
  - name: update-npm
    before: |
      npm install -g npm@11.4.2
      